# Generated by Django 4.1.7 on 2023-06-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dataset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesLoading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Не более 12 знаков",
                        max_digits=12,
                        null=True,
                        verbose_name="Код",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Не более 200 знаков", max_length=200
                    ),
                ),
                (
                    "sales",
                    models.PositiveIntegerField(default=1, verbose_name="Sold,шт."),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="'2022-08-18", null=True, verbose_name="Дата"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа-Loading",
                "verbose_name_plural": "Продажи-Loading",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Не более 12 знаков",
                        max_digits=12,
                        null=True,
                        verbose_name="Код",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            (None, "Выбрать ед.изм."),
                            ("кг", "кг"),
                            ("л", "л"),
                            ("шт.", " шт."),
                        ],
                        default="шт.",
                        max_length=10,
                        null=True,
                        verbose_name="Ед.изм.",
                    ),
                ),
                (
                    "unit_cost",
                    models.PositiveIntegerField(default=1, verbose_name="cost, руб"),
                ),
                (
                    "price",
                    models.PositiveIntegerField(default=1, verbose_name="Цена, руб"),
                ),
                (
                    "sales",
                    models.PositiveIntegerField(default=1, verbose_name="Sales,шт."),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Не более 10 знаков",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Не более 10 знаков",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="'2022-08-18", null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "weekday",
                    models.PositiveIntegerField(null=True, verbose_name="День недели"),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_sale",
                        to="dataset.categorygoods",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="name_sale",
                        to="dataset.goods",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа",
                "verbose_name_plural": "Продажи",
                "ordering": ["-date"],
            },
        ),
    ]
