# Generated by Django 4.1.7 on 2023-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasales", "0003_alter_sales_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="sales",
            field=models.PositiveIntegerField(default=1, verbose_name="Продано,шт."),
        ),
        migrations.AlterField(
            model_name="salesloading",
            name="sales",
            field=models.PositiveIntegerField(default=1, verbose_name="Продано,шт."),
        ),
    ]
