# Generated by Django 4.1.7 on 2023-06-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dataset", "0001_initial"),
        ("datasales", "0004_alter_sales_sales_alter_salesloading_sales"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesByCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales",
                    models.PositiveIntegerField(default=1, verbose_name="Продажи,руб."),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="'2022-08-18", null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_code",
                        to="dataset.categorygoods",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_name",
                        to="dataset.categorygoods",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа-Category",
                "verbose_name_plural": "Продажи-Category",
                "ordering": ["name"],
            },
        ),
    ]
