# Generated by Django 4.1.7 on 2023-06-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasales", "0005_salesbycategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesloading",
            name="sales",
        ),
        migrations.AddField(
            model_name="salesloading",
            name="gross_profit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Не более 10 знаков",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesloading",
            name="revenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Не более 10 знаков",
                max_digits=10,
                null=True,
            ),
        ),
    ]
