# Generated by Django 4.1.7 on 2023-06-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "datasales",
            "0006_remove_salesloading_sales_salesloading_gross_profit_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesbycategory",
            name="sales",
        ),
        migrations.RemoveField(
            model_name="salesloading",
            name="gross_profit",
        ),
        migrations.RemoveField(
            model_name="salesloading",
            name="revenue",
        ),
        migrations.AddField(
            model_name="salesbycategory",
            name="gross_profit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Не более 10 знаков",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesbycategory",
            name="revenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Не более 10 знаков",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesloading",
            name="sales",
            field=models.PositiveIntegerField(default=1, verbose_name="Продано,шт."),
        ),
    ]
