# Generated by Django 4.1.7 on 2023-06-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasales", "0007_remove_salesbycategory_sales_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesbycategory",
            name="code",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="6 цифр",
                max_digits=6,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salesbycategory",
            name="name",
            field=models.CharField(
                db_index=True,
                default="0",
                help_text="Не более 200 знаков",
                max_length=200,
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
