# Generated by Django 4.1.7 on 2023-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasales", "0008_alter_salesbycategory_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesbycategory",
            name="code",
            field=models.DecimalField(
                decimal_places=0, help_text="6 цифр", max_digits=6
            ),
        ),
    ]
