# Generated by Django 4.1.7 on 2023-06-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasales", "0009_alter_salesbycategory_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesbycategory",
            name="weekday",
            field=models.PositiveIntegerField(null=True, verbose_name="День недели"),
        ),
    ]
