# Generated by Django 4.1.7 on 2023-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasales", "0010_salesbycategory_weekday"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesBySupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.DecimalField(
                        decimal_places=0, help_text="6 цифр", max_digits=6
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Не более 200 знаков",
                        max_length=200,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="'2022-08-18", null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "weekday",
                    models.PositiveIntegerField(null=True, verbose_name="День недели"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Не более 10 знаков",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Не более 10 знаков",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа-Supplier",
                "verbose_name_plural": "Продажи-Supplier",
                "ordering": ["name"],
            },
        ),
    ]
