# Generated by Django 4.1.7 on 2023-07-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForecastCategorySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="'2022-08-18", null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "weekday",
                    models.PositiveIntegerField(null=True, verbose_name="День недели"),
                ),
                (
                    "code",
                    models.DecimalField(
                        decimal_places=0, help_text="6 цифр", max_digits=6
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Не более 200 знаков",
                        max_length=200,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Не более 10 знаков",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
