# Generated by Django 4.1.7 on 2023-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataforecast", "0002_alter_forecastcategorysales_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastcategorysales",
            name="median_error",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=6, null=True
            ),
        ),
    ]
