# Generated by Django 4.1.7 on 2023-07-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataforecast", "0003_forecastcategorysales_median_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastItemSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="'2022-08-18", null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "weekday",
                    models.PositiveIntegerField(null=True, verbose_name="День недели"),
                ),
                (
                    "code",
                    models.DecimalField(
                        decimal_places=0, help_text="6 цифр", max_digits=6
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Не более 200 знаков",
                        max_length=200,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "revenue_forecast",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Не более 10 знаков",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "item_forecast",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогноз Продаж по Товарам",
                "verbose_name_plural": "Прогнозы Продаж по Товарам",
                "ordering": ["name"],
            },
        ),
    ]
