# Generated by Django 4.1.7 on 2023-07-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataforecast", "0004_forecastitemsales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastitemsales",
            name="code",
            field=models.DecimalField(
                decimal_places=0, help_text="12 цифр", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="forecastitemsales",
            name="item_forecast",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="forecastitemsales",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Не более 200 знаков",
                max_length=200,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="forecastitemsales",
            name="revenue_forecast",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
