# Generated by Django 4.1.7 on 2023-07-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataforecast", "0005_alter_forecastitemsales_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastitemsales",
            name="code",
            field=models.IntegerField(),
        ),
    ]
