# Generated by Django 4.1.7 on 2023-07-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataforecast", "0006_alter_forecastitemsales_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastitemsales",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Не более 200 знаков",
                max_length=200,
                verbose_name="Категория",
            ),
        ),
    ]
